server:
  port: 9990

dubbo:
  application:
    name: dubboCustom
  registry:
    address: zookeeper://10.134.94.105:2181
  protocol:
    name: dubbo
    port: 20800

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springbatch?characterEncoding=utf8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true